export const ROLES = [
  'Academic researcher',
  'Database administrator',
  'Data or business analyst',
  'Data scientist or machine learning specialist',
  'Designer',
  'Developer, back-end',
  'Developer, desktop or enterprise applications',
  'Developer, embedded applications or devices',
  'Developer, front-end',
  'Developer, full-stack',
  'Developer, game or graphics',
  'Developer, mobile',
  'Developer, QA or test',
  'DevOps specialist',
  'Educator',
  'Engineer, data',
  'Engineer, site reliability',
  'Engineering manager',
  'Marketing or sales professional',
  'Product manager',
  'Scientist',
  'Senior executive/VP',
  'Student',
  'System administrator',
];

export const TECHNOLOGIES = [
  'JavaScript',
  'HTML/CSS',
  'SQL',
  'Python',
  'Java',
  'Bash/Shell/PowerShell',
  'C#',
  'PHP',
  'C++',
  'TypeScript',
  'C',
  'Ruby',
  'Go',
  'Assembly',
  'Swift',
  'Kotlin',
  'R',
  'VBA',
  'Objective-C',
  'Scala',
  'Rust',
  'Dart',
  'Elixir',
  'Clojure',
  'WebAssembly',
];

export const EXPERIENCE = [
  '5 to 9 years',
  '10 to 14 years',
  '15 to 19 years',
  '20 to 24 years',
  '25 to 29 years',
  '30 to 34 years',
  '35 to 39 years',
  '40 to 44 years',
  '45 to 49 years',
  '50 years or more',
  'Less than 5 years',
];

export const EDUCATION = [
  'Associate degree',
  "Bachelor's degree",
  'Doctoral degree',
  'I never completed any formal education',
  "Master's degree",
  'Primary/elementary school',
  'Professional degree',
  'Secondary school',
  'Some college/university study without earning a degree',
];
